#VT_Enricher.py
#Reference: API Integration
import json
import requests
import os
import sys

#Config Parsing: Managing API Key
API_KEY= os.environ.get('VT_API_KEY', 'YOUR VIRUS TOTAL API KEY')
VT_URL = "https://www.virustotal.com/api/v3/files/"

def query_vt(file_hash):
    """Interaction API VirusTotal"""
    headers = {"x-apikey": API_KEY}

    # Error Handle: Managing API Issues
    try:
        response = requests.get(f"{VT_URL}{file_hash}", headers=headers, timeout=10)
        if response.status_code == 200:
            return response.json()
        elif response.status_code == 404:
            return None # Hash not found in VT database
    except requests.exceptions.RequestException as e:
        print(f"API_Error: {e}")
        return None
    
def main():
    #Directoy Assignment
    ScriptDir = os.path.dirname(os.path.abspath(sys.argv[0]))
    InputFilePath = os.path.join(ScriptDir, 'hashes.json')
    #File I/O: Reading JSON generated by PS1
    if not os.path.exists(r"C:/PATH/FOR/HASHES.JSON"):
        print("File 'hashes.json' not found. Run PS1 script first")
        sys.exit(1)

    with open('C:/PATH/FOR/HASHES.JSON', 'r', encoding="utf-8-sig") as f:
        # List of dictionaries
        scan_data = json.load(f)
        
    report_output = []

    #Loop and Conditionals
    print("Starting Enrichemnt")
    for item in scan_data:
        vt_results = query_vt(item['Hash'])

        status = "Clean"
        if vt_results:
            stats = vt_results['data']['attributes']['last_analysis_stats']
            if stats['malicious'] > 0:
                status = "MALICIOUS"
                print(f"WARNING: {item['FileName']} is malicious")

        #Analytics
        item['Reputation'] = status
        report_output.append(item)

    #Output: JSON
    script_dir = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(script_dir, 'final_report.json')

    with open(file_path, 'w') as output:
        json.dump(report_output, output, indent=4)

    print(f"JSON report Created: {file_path}")


if __name__ == "__main__":
    main()